const ctrlD = "CTRL_PLUS_D";
const ctrlE = "CTRL_PLUS_E";
const AUDIO = "AUDIO";
const VIDEO = "VIDEO";

const TOGGLE_VIDEO_CONTROL = "TOGGLE_VIDEO_CONTROL";
const TOGGLE_AUDIO_CONTROL = "TOGGLE_AUDIO_CONTROL";
